// @vitest-environment jsdom
import { beforeEach, describe, expect, it } from 'vitest';
import { computeSignature } from '../../src/page/signature';

beforeEach(() => {
  document.body.innerHTML = '';
});

describe('computeSignature', () => {
  it('prefers a stable id over a class at the same level', () => {
    document.body.innerHTML =
      '<span id="checkout-total" class="css-1x2y3z">$1.500</span>';
    const el = document.querySelector('span')!;

    const result = computeSignature(el);

    expect(result.signature).toBe('#checkout-total');
    expect(result.signatureGroup).toBe('#checkout-total');
  });

  it('prefers data-testid over a class at the same level', () => {
    document.body.innerHTML =
      '<span data-testid="price-box" class="amount">$1.500</span>';
    const el = document.querySelector('span')!;

    const result = computeSignature(el);

    expect(result.signature).toBe('[data-testid="price-box"]');
  });

  it('falls back to nth-child when the only class looks autogenerated', () => {
    document.body.innerHTML =
      '<ul id="listing"><li class="sc-a1b2c3">$1.500</li></ul>';
    const li = document.querySelector('li')!;

    const result = computeSignature(li);

    expect(result.signature).toBe('#listing > :nth-child(1)');
    expect(result.signatureGroup).toBe('#listing > li');
  });

  it('gives sibling rows the same group signature but different positional signatures', () => {
    document.body.innerHTML = `
      <ul class="listing">
        <li class="sc-1a2b3c"><span class="price">$1.500</span></li>
        <li class="sc-4d5e6f"><span class="price">$2.300</span></li>
      </ul>
    `;
    const prices = Array.from(document.querySelectorAll('.price'));
    const [first, second] = prices.map((el) => computeSignature(el));

    expect(first!.signature).not.toBe(second!.signature);
    expect(first!.signatureGroup).toBe(second!.signatureGroup);
  });

  it('does not give an unrelated container the same group signature', () => {
    document.body.innerHTML = `
      <div class="product-card"><span class="price">$1.500</span></div>
      <div class="sidebar"><span class="promo">$999</span></div>
    `;
    const price = computeSignature(document.querySelector('.price')!);
    const promo = computeSignature(document.querySelector('.promo')!);

    expect(price.signatureGroup).not.toBe(promo.signatureGroup);
  });

  it('stops at body and never includes it', () => {
    document.body.innerHTML = '<span>$1.500</span>';
    const result = computeSignature(document.querySelector('span')!);

    expect(result.signature).toBe(':nth-child(1)');
    expect(result.signatureGroup).toBe('span');
  });

  it('caps the climb at maxLevels ancestors', () => {
    document.body.innerHTML = `
      <div class="l1"><div class="l2"><div class="l3"><div class="l4">
        <div class="l5"><div class="l6"><span>$1.500</span></div></div>
      </div></div></div></div>
    `;
    const result = computeSignature(document.querySelector('span')!, 2);

    expect(result.signature.split(' > ')).toHaveLength(2);
  });

  it('does not flag a short numeric class suffix as autogenerated', () => {
    document.body.innerHTML = '<div class="col-6">$1.500</div>';
    const result = computeSignature(document.querySelector('div')!);

    expect(result.signature).toBe('.col-6');
  });
});
