const LONG_DIGIT_RUN = /\d{4,}/;
const MIXED_ALPHANUMERIC_SEGMENT = /^(?=.*[a-z])(?=.*\d)[a-z0-9]{4,}$/i;

/**
 * Whether an id, class or data attribute value looks autogenerated (CSS
 * modules, styled-components and similar), per DISENO.md section 6.2:
 * either a long run of digits, or a hyphen/underscore-separated segment
 * that mixes letters and digits (`css-1x2y3z`, `sc-a1b2c3`).
 */
function looksAutoGenerated(value: string): boolean {
  if (LONG_DIGIT_RUN.test(value)) return true;
  return value
    .split(/[-_]/)
    .some((segment) => MIXED_ALPHANUMERIC_SEGMENT.test(segment));
}

const ARU_DATA_ATTRIBUTE_PREFIX = 'data-aru-';

function findSemanticDataAttribute(element: Element): Attr | undefined {
  const testId = element.attributes.getNamedItem('data-testid');
  if (testId?.value && !looksAutoGenerated(testId.value)) return testId;

  for (const attr of Array.from(element.attributes)) {
    if (!attr.name.startsWith('data-')) continue;
    if (attr.name.startsWith(ARU_DATA_ATTRIBUTE_PREFIX)) continue;
    if (!attr.value || looksAutoGenerated(attr.value)) continue;
    return attr;
  }

  return undefined;
}

function siblingIndex(element: Element): number {
  if (!element.parentElement) return 1;
  return (
    Array.prototype.indexOf.call(element.parentElement.children, element) + 1
  );
}

type LevelDescriptor = {
  location: string;
  group: string;
};

/**
 * Picks the most stable descriptor for one level of the signature, in the
 * priority order of DISENO.md section 6.2: stable `#id`, semantic
 * `data-*` attribute, first semantic-looking class, and `:nth-child(n)` as
 * the last resort. Only the last resort carries positional information, so
 * it is the only one that differs between `location` and `group`.
 */
function describeLevel(element: Element): LevelDescriptor {
  if (element.id && !looksAutoGenerated(element.id)) {
    const descriptor = `#${element.id}`;
    return { location: descriptor, group: descriptor };
  }

  const dataAttribute = findSemanticDataAttribute(element);
  if (dataAttribute) {
    const descriptor = `[${dataAttribute.name}="${dataAttribute.value}"]`;
    return { location: descriptor, group: descriptor };
  }

  const semanticClass = Array.from(element.classList).find(
    (className) => !looksAutoGenerated(className),
  );
  if (semanticClass) {
    const descriptor = `.${semanticClass}`;
    return { location: descriptor, group: descriptor };
  }

  return {
    location: `:nth-child(${siblingIndex(element)})`,
    group: element.tagName.toLowerCase(),
  };
}

/** The two signature variants of a container, per DISENO.md section 6.2/6.3. */
export type ContainerSignature = {
  /** Exact structural signature, including positional descriptors. */
  signature: string;

  /** Structural signature with positional descriptors removed. */
  signatureGroup: string;
};

const DEFAULT_MAX_LEVELS = 5;

/**
 * Computes the structural signature of a container, climbing from `element`
 * through its ancestors up to `maxLevels` or until `body`, per DISENO.md
 * section 6.2. `element` should be the container that actually held the
 * detected text in the page, never the `[data-aru-wrap]` span the extension
 * itself inserts.
 *
 * @param {Element} element The container to compute the signature for.
 * @param {number} [maxLevels] Maximum number of ancestor levels to climb. Defaults to 5.
 * @returns {ContainerSignature} The positional and generalized signatures.
 */
export function computeSignature(
  element: Element,
  maxLevels: number = DEFAULT_MAX_LEVELS,
): ContainerSignature {
  const locations: Array<string> = [];
  const groups: Array<string> = [];

  let current: Element | null = element;
  let levels = 0;

  while (
    current &&
    current !== current.ownerDocument.body &&
    levels < maxLevels
  ) {
    const { location, group } = describeLevel(current);
    locations.unshift(location);
    groups.unshift(group);
    current = current.parentElement;
    levels += 1;
  }

  return {
    signature: locations.join(' > '),
    signatureGroup: groups.join(' > '),
  };
}
